### DISCUSSION TITLE
Recommended deployment method?

### DISCUSSION THREAD

**Discussion by maworsham** [openbao/openbao#1466] [Q&A]
My environment is a little bit tricky as we needed Hashicorp's Vault for our [Ceph](https://ceph.io/en/) environment for handling encrypted RADOS Gateway [RGW](https://docs.ceph.com/en/latest/radosgw/vault/) S3 Buckets. Through the help of a system integrator, we have our entire Vault cluster setup and configured using a set of custom designed Ansible playbooks along with the [ansible-community.ansible-vault](https://github.com/ansible-community/ansible-vault) repo. Each vault server is setup individually, so they aren't running docker or Kubernetes. At the moment we are running the Vault Enterprise 'Plus' license but exploring our options since we aren't really using any of what is offered with the enterprise license and wondering if we can just use either OSS Vault or the OpenBao platform instead.

When I was looking over the "[Installing OpenBao](https://openbao.org/docs/install/)" page, there isn't exactly a recommendation for how to deploy OpenBao. 

For those of us that are unfamiliar with container-like apps (i.e., Docker, Kubernetes), what would be the recommended approach for setting up an OpenBao cluster? Is there a quick to-do / setup deployment guide or even an Ansible playbook for setting it up and deploying it?

**Comment by dc-tec** [comment]
Hey @maworsham. It's a bit late of a reply. But we have created an Ansible role that can help with the deployment of OpenBao: https://github.com/robertdebock/ansible-role-openbao.

**Comment by supun-io** [comment]
Also, is Docker-based deployment recommended for production? The [Dockerfile](https://github.com/openbao/openbao/blob/main/Dockerfile#L155) itself is written for development with the `-dev` flag. 

I got it working with a Traefik/OpenBao/Postgres set up with Docker:

- Single server deployment
- Traefik terminates TLS, TLS disabled in OpenBao (Docker networking)
- OpenBao listens on `http://0.0.0.0:8200`
- Postgres as storage (easier with our current backup system)

```
services:
  traefik:
    image: traefik:3.5
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsEncrypt.acme.email=..."
      - "--certificatesresolvers.letsEncrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsEncrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/user/letsencrypt:/letsencrypt"

  openbao:
    image: openbao/openbao:2.4.3
    container_name: openbao
    restart: unless-stopped
    command: ["server", "-config=/etc/openbao/openbao.hcl"]
    volumes:
      - ./openbao.hcl:/etc/openbao/openbao.hcl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbao.rule=Host(`myhost.mywebsite.com`)"
      - "traefik.http.routers.openbao.entrypoints=websecure"
      - "traefik.http.routers.openbao.tls.certresolver=letsEncrypt"
      - "traefik.http.services.openbao.loadbalancer.server.port=8200"

  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=openbao
      - POSTGRES_PASSWORD=...
      - POSTGRES_DB=openbao_db
    volumes:
      - openbao_postgres_data:/var/lib/postgresql

volumes:
  openbao_postgres_data:
```

Any suggestions on how secure this might be? And if a Docker deployment is recommended for production?
