### ISSUE TITLE
kubernetes auth doesn't seem to work for openbao

### ISSUE THREAD

**Issue by dvrkl** [openbao/openbao#345]
**Describe the bug**
Kubernetes auth doesn't seem to work openbao
Fails with the following error:
`{"errors":["permission denied"]}`

**To Reproduce**
Followed steps from here: https://support.hashicorp.com/hc/en-us/articles/4404389946387-Kubernetes-auth-method-Permission-Denied-error
1. kubectl create namespace test
2.  
``` cat <<EOF | kubectl create -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-cloud
  namespace: test
---
apiVersion: v1
kind: Secret
metadata:
 name: test-cloud
 namespace: test
 annotations:
   kubernetes.io/service-account.name: test-cloud
type: kubernetes.io/service-account-token
EOF
```
3. cat <<EOF | kubectl create -f -
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
  - kind: ServiceAccount
    name: test-cloud
    namespace: test
EOF
```
4. bao auth enable kubernetes
5. TOKEN_REVIEW_JWT=$(kubectl get secret vault-auth -o go-template='{{ .data.token }}' | base64 --decode) 
6. KUBE_CA_CERT=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)
7. KUBE_HOST=$(kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.server}')
8. bao write auth/kubernetes/config   token_reviewer_jwt="$TOKEN_REVIEW_JWT"   kubernetes_host="$KUBE_HOST"   kubernetes_ca_cert="$KUBE_CA_CERT" disable_local_ca_jwt="true"
9. Verify with `vault read auth/kubernetes/config`
10. Create policy
```
bao policy write devwebapp - <<EOF
path "secret/data/devwebapp/config" {
  capabilities = ["read"]
}
EOF
```
11. Create role
```
bao write auth/kubernetes/role/devweb-app \
  bound_service_account_names=test-cloud \
  bound_service_account_namespaces=test \
  policies=devwebapp \
  ttl=24h
```
12. `TOKEN_REVIEW_SJWT=$(kubectl get secret  test-cloud -n test -o go-template='{{ .data.token }}' | base64 --decode)`
13. Try login
curl --request POST --data '{"jwt": "'$TOKEN_REVIEW_SJWT'", "role": "devweb-app"}'  http://127.0.0.1:8200/v1/auth/kubernetes/login

**Expected behavior**
Success! Data written to: auth/kubernetes/role/devweb-app

**Environment:**
* OpenBao Server Version (retrieve with `bao status`):
```
$ bao status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         2.0.0-alpha20240329
Build Date      2024-05-03T17:07:26Z
Storage Type    inmem
Cluster Name    vault-cluster-2e665ce1
Cluster ID      9b565d27-727e-0671-7fb5-4876bd201768
HA Enabled      false
```
* OpenBao CLI Version (retrieve with `bao version`):
```
$ bao version
OpenBao v2.0.0-alpha20240329 ('a5e299de79465b922076f415e8945efaf0c9eb91'), built 2024-05-03T17:07:26Z
```
* Server Operating System/Architecture:

OpenBao server configuration file(s):

```hcl
# Paste your OpenBao config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by denispeyrusaubes** [comment]
same problem... does anybody success in using openbao deployed in Kubernetes ?

**Comment by cipherboy** [comment]
@denispeyrusaubes Do you have any logs or anything? Perhaps if this is a test environment, [raw](https://openbao.org/docs/audit/#common-configuration-options) [audit logs](https://openbao.org/api-docs/system/audit/)? I'm curious what is going wrong.

**Comment by ajaygk95** [comment]
I have been using openbao on Kubernetes and did not face any auth issues.
I will update more shortly on the config and setup I have been using

**Comment by ajaygk95** [comment]
Create a service account `bao-sa` with `system:auth-delegator` role attached. You can use the below yaml

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bao-auth-delegator
  namespace: ajay-new
subjects:
- kind: ServiceAccount
  name: bao-sa
  namespace: ajay-new
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bao-sa
  namespace: ajay-new
automountServiceAccountToken: true
```

Create an application service account which will be used for authentication

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-application
  namespace: ajay-new
automountServiceAccountToken: true
```

Get the below env's

```
export KUBE_HOST=$(kubectl get svc kubernetes -o jsonpath='{.spec.clusterIP}')
export SECRET_NAME=$(kubectl get sa bao-sa -n ajay-new -o jsonpath='{.secrets[0].name}')
export SA_TOKEN=$(kubectl get secret ${SECRET_NAME}  -n ajay-new -o jsonpath='{.data.token}' | base64 --decode)
echo $KUBE_HOST
echo $KUBE_CERT
echo $SA_TOKEN
```

Login into the openbao pod

```
export KUBE_HOST=<>
export SA_TOKEN=<>
export KUBE_CERT=$(cat /run/secrets/kubernetes.io/serviceaccount/ca.crt)

export BAO_ADDR='https://127.0.0.1:8200'
export BAO_SKIP_VERIFY=True
export BAO_TOKEN=<>
bao login ${BAO_TOKEN}
```

Enable and configure kube-auth

```
bao auth enable -path kubernetes kubernetes
bao write auth/kubernetes/config kubernetes_host="https://${KUBE_HOST}"  token_reviewer_jwt=${SA_TOKEN} kubernetes_ca_cert="${KUBE_CERT}" disable_local_ca_jwt=true

bao read auth/kubernetes/config
Key                       Value
---                       -----
disable_iss_validation    true
disable_local_ca_jwt      true
issuer                    n/a
kubernetes_ca_cert        ...
kubernetes_host           https://10.254.0.1
pem_keys                  []
token_reviewer_jwt_set    true
```

Configure kube-auth to `test-application` service account.
Create a role to read from kv-v2 secrets, enable kv-v2 and create a secret

```
bao write auth/kubernetes/role/static-secret bound_service_account_names=test-application bound_service_account_namespaces=ajay-new policies=read-kvv2 ttl=24h

bao policy write read-kvv2 - <<EOF
path "kvv2/*" {
   capabilities = ["read"]
}
EOF

bao secrets enable -path=kvv2 kv-v2
bao kv put kvv2/user/creds db-password="root"
```

Login using `test-application` service account token, to obtain a client token. Use client token to fetch the kv-v2 secret

```
export APP_SECRET_NAME=$(kubectl get sa test-application -n ajay-new -o jsonpath='{.secrets[0].name}')
export APP_SA_TOKEN=$(kubectl get secret ${APP_SECRET_NAME} -n ajay-new -o jsonpath='{.data.token}' | base64 --decode)

export CLIENT_TOKEN=$(curl -k -s -X POST --data '{"role":"static-secret", "jwt":"'"$APP_SA_TOKEN"'"}' https://openbao.ajay-new.svc.cluster.local:8200/v1/auth/kubernetes/login | jq -r '.auth.client_token')
echo $CLIENT_TOKEN

curl --insecure --header "X-Vault-Token: ${CLIENT_TOKEN}" https://openbao.ajay-new.svc.cluster.local:8200/v1/kvv2/data/user/creds
```
